version: "2.0"
services:
  db:
    volumes:
      - ./db:/db
  lb:
    depends_on:
      - ssl_check
  ssl_check:
    build: ./ssl
    volumes_from:
      - ssl_volume
  imageDownload:
    container_name: imageDownload
    image: schickling/s3cmd
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    command: -v --progress --no-preserve --cache-file=/images/s3cache sync s3://ovrride/wp-content/uploads /images/uploads/
    volumes:
      - ./images:/images
  dbDownload:
    container_name: dbDownload
    image: schickling/s3cmd
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - ./db:/db
    command: get --exclude="*" --rinclude="ovrride_([0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}h[0-9]{2}m\.[MTWFS][ouehra][neduit][dsnru][adesr][sday]{1,3}|week\.[0-9]{2}\.[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}h[0-9]{2}m)\.sql\.gz" -f s3://ovrdatabase/latest/* /db/ovrride.sql.gz
    depends_on:
      - db
  dbImport:
    container_name: dbImport
    image: univunix/alpine-mariadb
    environment:
      - REMOTE_DB_USER=dev
      - REMOTE_DB_PASS=Afq8vcPM99W2IsiptfivPInYorpznBY2fryKyHlbo6FOCxZ4cs6HSseFNmaw81G
    volumes:
      - ./db:/db
      - ./scripts/dbImport.sh:/dbImport.sh
      - ./scripts/pv:/usr/local/bin/pv
      - ./scripts/ovr_dev.sql:/ovr_dev.sql
    depends_on:
      - dbDownload
    links:
      - db
    entrypoint: /bin/sh
    command: /dbImport.sh
