version: "2.0"
services:
  db_backup:
    build: ./db_backup
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    env_file: ./dev.env
    links:
      - db
  rbb_code:
    build: ./rbb_code
  ovr_code:
    build:
      context: ./ovr_code
      dockerfile: dockerfile-production
  ovr_web:
    environment:
      - VIRTUAL_HOST=http://ovrride.com,http://www.ovrride.com,https://ovrride.com,https://www.ovrride.com
      - HOST_NAME=ovrride.com
  rbb_web:
    environment:
      - VIRTUAL_HOST=http://rockawaybeachbus.com,https://rockawaybeachbus.com
  ovr_lists:
    environment:
      - VIRTUAL_HOST=https://lists.ovrride.com, http://lists.ovrride.com
  image_sync:
    build: ./image_sync
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes_from:
      - ovr_web
