version: "2.0"
services:
  db:
    build: ./mariadb
    cpu_shares: 1024
    mem_limit: 2147483648
    environment:
      - DB_USER=dev
      - DB_PASS=Afq8vcPM99W2IsiptfivPInYorpznBY2fryKyHlbo6FOCxZ4cs6HSseFNmaw81G
      - DB_ROOT_PASS=vWKLWhf7LkCegEPvpe8MWUhVrq0NPcpFDC7rxR7VECwQ7dS4zRyuEFYOkcdC3L6
    volumes_from:
      - db_data
  db_data:
    image: tianon/true
    volumes:
      - /data/db/mysql
  memcached:
    image: alloylab/memcached
    cpu_shares: 64
  ovr_hhvm:
    build: ./hhvm
    cpu_shares: 512
    mem_limit: 1073741824
    volumes_from:
      - ovr_code
    env_file: ./dev.env
    links:
      - memcached
      - db
  php:
    build: ./php7
    cpu_shares: 512
    mem_limit: 1073741824
    volumes:
      - ${OVRGIT}:/ovrride:rw
      - ${LISTSGIT}:/lists:rw
      - ${RBBGIT}:/rbb:rw
      - ./images/uploads:/ovrride/wp-content/uploads:rw
    env_file: ./dev.env
    links:
      - memcached
      - db
  ovr_web:
    image: nginx:alpine
    cpu_shares: 128
    environment:
      - VIRTUAL_HOST=http://ovrride.dev,http://www.ovrride.dev,https://ovrride.dev,https://www.ovrride.dev
    expose:
      - "80"
      - "443"
    volumes_from:
      - ovr_code
    volumes:
      - ./conf/nginx/ovr.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/hhvm.conf:/etc/nginx/hhvm.conf
    depends_on:
      - db
    links:
      - memcached
      - ovr_hhvm:hhvm
      - php
  rbb_hhvm:
    build: ./hhvm
    cpu_shares: 96
    volumes_from:
      - rbb_code
    env_file: ./dev.env
    links:
      - ovr_web
  rbb_web:
    image: nginx:alpine
    cpu_shares: 25
    environment:
      - VIRTUAL_HOST=http://rockawaybeachbus.dev,https://rockawaybeachbus.dev
    volumes_from:
      - rbb_code
    volumes:
      - ./conf/nginx/rbb.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/hhvm.conf:/etc/nginx/hhvm.conf
    depends_on:
      - ovr_web
    links:
      - rbb_hhvm:hhvm
      - php
  rbb_code:
    image: alpine:3.4
    volumes:
      - ${RBBGIT}:/usr/share/nginx/rbb/
    command: ["true"]
  ovr_lists:
    image: nginx:alpine
    cpu_shares: 25
    environment:
      - VIRTUAL_HOST=https://lists.ovrride.dev, http://lists.ovrride.dev
      - FORCE_SSL=true
    links:
      - php
    depends_on:
      - db
    volumes_from:
      - php
    volumes:
      - ./conf/nginx/lists.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/php.conf:/etc/nginx/php.conf
      - ./conf/nginx/mime.types:/etc/nginx/mime.types
  lb:
    image: dockercloud/haproxy
    cpu_shares: 512
    mem_limit: 536870912
    environment:
      - CERT_FOLDER=/certs/
      - SSL_BIND_CIPHERS=ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
      - EXTRA_GLOBAL_SETTINGS=tune.ssl.default-dh-param 2048
      - TIMEOUT=connect 10000, client 100000, server 100000
    links:
      - ovr_web
      - rbb_web
      - ovr_lists
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - ssl_volume
    ports:
      - 80:80
      - 443:443
      - 1936:1936
  cron:
    build: ./cron
    cpu_shares: 25
    env_file: ./dev.env
    links:
      - ovr_web
      - rbb_web
  ssl_volume:
    image: tianon/true
    volumes:
      - /certs
  ovr_code:
    build: ./ovr_code
    volumes:
      - ${OVRGIT}/wp-content:/usr/share/nginx/wordpress/wp-content
      - ./images/uploads/uploads:/usr/share/nginx/wordpress/wp-content/uploads
