version: "2.0"
services:
  db_backup:
    build: ./db_backup
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    env_file: ./dev.env
    links:
      - db
  rbb_code:
    build: ./rbb_code
