version: "2.0"
services:
  rbb_hhvm:
    build: ./hhvm
    cpu_shares: 96
    volumes_from:
      - rbb_code
    env_file: ./dev.env
    links:
      - ovr_web
  rbb_web:
    image: nginx:alpine
    cpu_shares: 25
    environment:
      - VIRTUAL_HOST=http://rockawaybeachbus.dev,https://rockawaybeachbus.dev
    volumes_from:
      - rbb_code
    volumes:
      - ./conf/nginx/rbb.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/rbb_hhvm.conf:/etc/nginx/hhvm.conf
    depends_on:
      - ovr_web
    links:
      - rbb_hhvm:hhvm
      - php
  rbb_code:
    image: alpine:3.4
    volumes:
      - ${RBBGIT}:/usr/share/nginx/rbb/
    command: ["true"]
  lb:
    links:
      - ovr_web
      - rbb_web
  rbb_cron:
    build:
      context: ./cron
      dockerfile: dockerfile-rbb
    cpu_shares: 25
    env_file: ./dev.env
    links:
      - rbb_web
