FROM php:5.6.33-fpm-jessie

RUN /usr/local/bin/docker-php-source extract

# Install other needed extensions
RUN apt-get update && apt-get install -y libsqlite3-dev libfreetype6 libjpeg62-turbo libmcrypt4 libpng12-0 sendmail --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN buildDeps=" \
		libfreetype6-dev \
		libjpeg-dev \
		libldap2-dev \
		libmcrypt-dev \
		libpng-dev \
		zlib1g-dev \
	"; \
	set -x \
	&& apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
	&& docker-php-ext-configure gd --enable-gd-native-ttf --with-jpeg-dir=/usr/lib/x86_64-linux-gnu --with-png-dir=/usr/lib/x86_64-linux-gnu --with-freetype-dir=/usr/lib/x86_64-linux-gnu \
	&& docker-php-ext-install gd \
	&& docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu \
	&& docker-php-ext-install ldap \
	&& docker-php-ext-install mbstring \
	&& docker-php-ext-install mcrypt \
	&& docker-php-ext-install mysqli \
	&& docker-php-ext-install pdo_mysql \
	&& docker-php-ext-install pdo_sqlite \
	&& docker-php-ext-install zip \
	&& apt-get purge -y --auto-remove $buildDeps && apt-get clean
RUN pecl install redis-3.1.4 && docker-php-ext-enable redis


# Setup timezone to Eastern Standard Time, max upload size to 100M and sessions to redis
RUN cp /usr/src/php/php.ini-production /usr/local/etc/php/php.ini
RUN sed -i'' 's/^;\(date.timezone.*\)/\1 \"America\/New_York"/' /usr/local/etc/php/php.ini
RUN sed -i'' 's/^\(upload_max_filesize\s*=\s*\).*\$/\1100M/' /usr/local/etc/php/php.ini
RUN sed -i'' 's/^\(post_max_size\s*=\s*\).*\$/\1100M/' /usr/local/etc/php/php.ini
RUN sed -i'' 's/^session.save_handler.*$/session.save_handler = redis/' /usr/local/etc/php/php.ini
RUN sed -i'' "s/^;session.save_path.*/session.save_path = 'tcp:\/\/redis:6379'/" /usr/local/etc/php/php.ini
RUN sed -i'' 's/^log_errors_max_len.*/log_errors_max_len = 0/' /usr/local/etc/php/php.ini
RUN sed -i'' 's/^pm.max_children.*/pm.max_children = 20/' /usr/local/etc/php-fpm.d/www.conf
RUN /usr/local/bin/docker-php-source delete
