FROM alpine:3.4
COPY ovr_wp_cron /bin/ovr_wp_cron
COPY rbb_cron /bin/rbb_cron
COPY crontab /var/spool/cron/crontabs/root
RUN chmod +x /bin/ovr_wp_cron && chmod +x /bin/rbb_cron && apk add --update curl && rm -rf /var/cache/apk/*
CMD crond -l 2 -f
